[package]
name = "bevy-getting-started"
version = "0.1.0"
edition = "2024"
authors = ["Ethan Uppal"]

[dependencies]
bevy = { version = "0.16.0-rc.4", features = ["dynamic_linking"] }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
